### ISSUE TITLE
Try to package on AUR

### ISSUE THREAD

**Issue by CoelacanthusHex** [ayaka14732/rime-putonghua#1]
依赖似乎有点多……

**Comment by CoelacanthusHex** [comment]
Link： https://aur.archlinux.org/packages/rime-putonghua/

暂时没有 cloud ……那个包的打包我遇上了点麻烦……

**Comment by CoelacanthusHex** [comment]
Done.
Maybe work.
为了打那个 lua 的还专门搞了个 hook…… https://github.com/ayalhw/rime-lua-hook
lua插件有毒…… 它只读那个 rime.lua ...

**Comment by ayaka14732** [comment]
好耶，妹妹好棒

---

我想 `PKGBUILD` 的 `prepare` 里面可以不需要 `ln` rime-liangfen，这样的话后面 `package` 里面也不需要 `rm build/liangfen.*` 了，因为 rime-liangfen 只是反查，`rime_deployer` 不用它也可以编译

**Comment by ayaka14732** [comment]
好像 librime-lua 只支持 `rime.lua` 放在用户文件夹里，因为 `rime.fcitx-rime.INFO` 里面有

```
I0822 11:07:29.834467 20467 modules.cc:32] registering components from module 'lua'.
I0822 11:07:29.834987 20467 modules.cc:24] rime.lua error: cannot open /home/ayaka/.local/share/fcitx5/rime/rime.lua: No such file or directory
```

源代码里面似乎只写了 `RimeGetUserDataDir()`，见 <https://github.com/hchunhui/librime-lua/blob/7a0c90bf160163690ee18284a017118a4df4521c/src/modules.cc#L9-L27>。

放在程序文件夹里的话云输入就不工作，放在用户文件夹里才可以。应该要修改一下 librime-lua 源代码。

**Comment by CoelacanthusHex** [comment]
> 我想 `PKGBUILD` 的 `prepare` 里面可以不需要 `ln` rime-liangfen，这样的话后面 `package` 里面也不需要 `rm build/liangfen.*` 了，因为 rime-liangfen 只是反查，`rime_deployer` 不用它也可以编译

嗯，看了看是这样的，我会在今天晚些时候改掉
